### ISSUE TITLE
Please read the devDependencies property

### ISSUE THREAD

**Issue by vvakame** [seanhess/tpm#1]
I was able to meet the future is a project that I am :)

I want to add devDependencies's .d.ts to process.

for example.
my bower.json is here.

```
{
...
    "dependencies": {
        "i18next": "1.6.3"
    },
    "devDependencies": {
        "jasmine": "1.3.1"
    },
...
}
```

in bower's semantics. devDependencies means "Dependencies that are only needed for development of the package, e.g., test framework or building documentation."
https://docs.google.com/document/d/1APq7oA9tNao1UYWyOm8dKqlRP2blVkROYLZ2fLIjtWc/edit#heading=h.s6stte97orx4

DefinitelyTyped has jasmine.d.ts 
https://github.com/borisyankov/DefinitelyTyped/blob/master/jasmine/jasmine.d.ts

I want to use it.

I'm expected how to use. like this.
`tpm install --with-dev-dependencies bower.json`

**Comment by seanhess** [comment]
Done. Use the following syntax:

```
tpm install --dev bower.json
```

**Comment by vvakame** [comment]
so quick!
Thank you sir :)
I'll try it tomorrow! AM2:00 now in Japan.
