### ISSUE TITLE
multiple targets for grunt

### ISSUE THREAD

**Issue by torvalde** [seanhess/tpm#5]
In the grunt task I would like to generate the typedef files for bower.json and package.json separately.

I have not found a way to do it with the current version,

The reason I want to do this to have one file for the libraries on the server, and one for the client libraries

**Comment by seanhess** [comment]
It should be possible now: 

```
grunt.initConfig({
    "tpm-install": {
      options: {dev: false},
      server: {src: "package.json", dest: "server-types/"},
      public: {src: "bower.json", dest: "public-types/"},
    },
})
```

**Comment by torvalde** [comment]
Yes, that is correct. My mistake. Thanks.
